name: annotations
version: 0.1.0-alpha.02
description: >
  Metadata annotations for unobstrutive instance variable valiation
author: Jamie Couperwhite <jcouperwhite@gmail.com>
homepage: https://github.com/jamcoupe/dart-annotations
dependencies:
  unittest: any